---
- name: This is a sample playbook to install httpd service
  hosts: webserver
  tasks:

    - name: Install httpd service
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Open firewall port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
