---
- name: Hardening linux server
  hosts: all
  become: true
  tasks:

  - name: Instalar pacotes basicos
    ansible.builtin.package:
      name:
        - vim
        - git
        - bind-utils
        - net-tools
      state: present

  - name: Remover pacotes
    ansible.builtin.package:
      name:
        - telnet
        - tcpdump
        - chrony
      state: absent

# configurar o chronyd
  - name: Install package chronyd
    ansible.builtin.package:
      name: chrony-4.2-1.el9.aarch64
      state: present

  - name: Copy config template
    ansible.builtin.copy:
      src: files/chrony.conf
      dest: /etc/chrony.conf

  - name: Start chrony server
    ansible.builtin.service:
      name: chronyd
      state: started
      enabled: true

  - name: Comando de test do chrony
    command: chronyc sourcestats
    register: cmd_chronyc

  - name: Output comando chronyc
    ansible.builtin.debug:
      var: cmd_chronyc

# configurar SELinux

  - name: Enable SELinux
    ansible.posix.selinux:
      policy: targeted
      state: enforcing

# desabilitar firewall local
  - name: Disable firewalld
    ansible.builtin.service:
      name: firewalld
      state: stopped